urls = ["https://www.glassdoor.com/index.htm",
        "https://www.glassdoor.com/Salaries/us-backend-developer-salary-SRCH_IL.0,2_IN1_KO3,20.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-senior-front-end-developer-salary-SRCH_IL.0,2_IN1_KO3,29.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-devops-salary-SRCH_IL.0,2_IN1_KO3,9.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-qa-engineering-salary-SRCH_IL.0,2_IN1_KO3,17.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-security-engineer-salary-SRCH_IL.0,2_IN1_KO3,20.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-ux-designer-salary-SRCH_IL.0,2_IN1_KO3,14.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-ui-designer-salary-SRCH_IL.0,2_IN1_KO3,14.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-tester-salary-SRCH_IL.0,2_IN1_KO3,9.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-data-engineer-salary-SRCH_IL.0,2_IN1_KO3,16.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-data-scientist-salary-SRCH_IL.0,2_IN1_KO3,17.htm?clickSource=searchBtn",
        "https://www.glassdoor.com/Salaries/us-software-architect-salary-SRCH_IL.0,2_IN1_KO3,21.htm?clickSource=searchBtn"]

mexico = ['https://www.glassdoor.com/Salaries/mexico-front-end-developer-salary-SRCH_IL.0,6_IN169_KO7,26.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-backend-developer-salary-SRCH_IL.0,6_IN169_KO7,24.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-devops-salary-SRCH_IL.0,6_IN169_KO7,13.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-qa-engineering-salary-SRCH_IL.0,6_IN169_KO7,21.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-security-engineer-salary-SRCH_IL.0,6_IN169_KO7,24.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-ux-designer-salary-SRCH_IL.0,6_IN169_KO7,18.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-ui-designer-salary-SRCH_IL.0,6_IN169_KO7,18.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-tester-salary-SRCH_IL.0,6_IN169_KO7,13.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-data-engineer-salary-SRCH_IL.0,6_IN169_KO7,20.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-data-scientist-salary-SRCH_IL.0,6_IN169_KO7,21.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/mexico-software-architect-salary-SRCH_IL.0,6_IN169_KO7,25.htm?clickSource=searchBtn']

colombia = ['https://www.glassdoor.com/Salaries/colombia-front-end-developer-salary-SRCH_IL.0,8_IN54_KO9,28.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-backend-developer-salary-SRCH_IL.0,8_IN54_KO9,26.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-devops-salary-SRCH_IL.0,8_IN54_KO9,15.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-qa-engineer-salary-SRCH_IL.0,8_IN54_KO9,20.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-security-engineer-salary-SRCH_IL.0,8_IN54_KO9,26.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-ux-designer-salary-SRCH_IL.0,8_IN54_KO9,20.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-ui-designer-salary-SRCH_IL.0,8_IN54_KO9,20.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-data-engineer-salary-SRCH_IL.0,8_IN54_KO9,22.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-data-scientist-salary-SRCH_IL.0,8_IN54_KO9,23.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/colombia-software-architect-salary-SRCH_IL.0,8_IN54_KO9,27.htm?clickSource=searchBtn']

brazil = ['https://www.glassdoor.com/Salaries/brazil-backend-developer-salary-SRCH_IL.0,6_IN36_KO7,24.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-front-end-developer-salary-SRCH_IL.0,6_IN36_KO7,26.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-devops-salary-SRCH_IL.0,6_IN36_KO7,13.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-qa-engineer-salary-SRCH_IL.0,6_IN36_KO7,18.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-security-engineer-salary-SRCH_IL.0,6_IN36_KO7,24.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-ux-designer-salary-SRCH_IL.0,6_IN36_KO7,18.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-ui-designer-salary-SRCH_IL.0,6_IN36_KO7,18.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-data-engineer-salary-SRCH_IL.0,6_IN36_KO7,20.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-data-scientist-salary-SRCH_IL.0,6_IN36_KO7,21.htm?clickSource=searchBtn',
        'https://www.glassdoor.com/Salaries/brazil-software-architect-salary-SRCH_IL.0,6_IN36_KO7,25.htm?clickSource=searchBtn']

argentina = ['https://www.glassdoor.com/Salaries/argentina-backend-developer-salary-SRCH_IL.0,9_IN15_KO10,27.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-front-end-developer-salary-SRCH_IL.0,9_IN15_KO10,29.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-devops-salary-SRCH_IL.0,9_IN15_KO10,16.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-qa-engineer-salary-SRCH_IL.0,9_IN15_KO10,21.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-security-engineer-salary-SRCH_IL.0,9_IN15_KO10,27.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-ux-designer-salary-SRCH_IL.0,9_IN15_KO10,21.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-ui-designer-salary-SRCH_IL.0,9_IN15_KO10,21.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-data-engineer-salary-SRCH_IL.0,9_IN15_KO10,23.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-data-scientist-salary-SRCH_IL.0,9_IN15_KO10,24.htm?clickSource=searchBtn',
             'https://www.glassdoor.com/Salaries/argentina-software-architect-salary-SRCH_IL.0,9_IN15_KO10,28.htm?clickSource=searchBtn']